config/routes.rb
ChronicCal4::Application.routes.draw do
  resources :assignments
  resource :calendar, :only => [:show]
  root :to => 'home#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  
  validate :check_starts_at_text
  
  scope :before, lambda {|end_time| {:conditions => ["ends_at < ?", Assignment.format_date(end_time)] }}
  scope :after, lambda {|start_time| {:conditions => ["starts_at > ?", Assignment.format_date(start_time)] }}
  
  # create the "ends_at" value like this:
    before_save :save_starts_at_text
    before_save :create_end
    
    # getter for starts_at
    attr_writer :starts_at_text
  
    # need to override the json view to return what full_calendar is expecting.
    # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
    def as_json(options = {})
      {
        :id => self.id,
        :title => self.title,
        :description => self.description || "",
        :start => starts_at.rfc822,
        :end => ends_at.rfc822,
        :allDay => self.all_day,
        :recurring => false,
        :className => self.assignment_type,
        :url => Rails.application.routes.url_helpers.assignment_path(id),
        #:color => "red"
      }

    end

      def starts_at_text
        #@starts_at_text || starts_at.try(:strftime, "%Y-%m-%d %H:%M:%S")
        @starts_at_text || starts_at.try(:strftime, "%A %b. %-e, %Y, %l:%M%p")
      end

      def save_starts_at_text
        self.starts_at = Chronic.parse(@starts_at_text) if @starts_at_text.present?
      end

      def check_starts_at_text
        if @starts_at_text.present? && Chronic.parse(@starts_at_text).nil?
          errors.add :starts_at_text, "cannot be parsed"
        end
      rescue ArgumentError
        errors.add :starts_at_text, "is out of range"
      end
  
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end

    private
    def create_end
      unless starts_at.nil?
    self.ends_at = starts_at.advance(:hours => duration_hours, :minutes => duration_minutes)
  end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  # GET /assignments
  # GET /assignments.json
  def index
    # full_calendar will hit the index method with query parameters
    # 'start' and 'end' in order to filter the results for the
    # appropriate month/week/day.  It should be possible to change
    # this to be starts_at and ends_at to match rails conventions.
    # I'll eventually do that to make the demo a little cleaner.
    @assignments = Assignment.scoped  
    @assignments = @assignments.after(params['start']) if (params['start'])
    @assignments = @assignments.before(params['end']) if (params['end'])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @assignments }
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @assignment }
    end
  end

  # GET /assignments/new
  # GET /assignments/new.json
  def new
    @assignment = Assignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @assignment }
    end
  end

  # GET /assignments/1/edit
  def edit
    @assignment = Assignment.find(params[:id])
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(params[:assignment])

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, :notice => 'Assignment was successfully created.' }
        format.json { render :json => @assignment, :status => :created, :location => @assignment }
      else
        format.html { render :action => "new" }
        format.json { render :json => @assignment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /assignments/1
  # PUT /assignments/1.json
  def update
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      if @assignment.update_attributes(params[:assignment])
        format.html { redirect_to @assignment, :notice => 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @assignment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

 def index
   redirect_to calendar_path
 end
 
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
  def assignment_type_options
     ['confirmed', 'tentative', 'personal']
   end
   def clarify_start_options
      ['ready at:', 'arrive at:']
    end
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :assignment_type %><br />
    <%= f.select(:assignment_type, assignment_type_options) %>
  </div>
  <div class="field">
    <%= f.label :clarify_start, 'Clarify Start:' %><br />
    <%= f.select(:clarify_start, clarify_start_options) %>
  </div>
  <div class="field">
    <%= f.label :starts_at_text, 'Starts at: ' %><br />
    <%= f.text_field :starts_at_text %>
  </div>
  <div class="field">
    <%= f.label :duration_hours %><br />
    <%= f.number_field :duration_hours %>
  </div>
  <div class="field">
    <%= f.label :duration_minutes %><br />
    <%= f.number_field :duration_minutes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<h1>Listing assignments</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Assignment type</th>
    <th>Starts at</th>
    <th>Duration hours</th>
    <th>Duration minutes</th>
    <th>Ends at</th>
    <th>All day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.title %></td>
    <td><%= assignment.description %></td>
    <td><%= assignment.assignment_type %></td>
    <td><%= assignment.starts_at.strftime("%A %b. %-e, %Y, %l:%M%p") %></td>
    <td><%= assignment.duration_hours %></td>
    <td><%= assignment.duration_minutes %></td>
    <td><%= assignment.ends_at.strftime("%A %b. %-e, %Y, %l:%M%p") %></td>
    <td><%= assignment.all_day %></td>
    <td><%= link_to 'Show', assignment %></td>
    <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
    <td><%= link_to 'Destroy', assignment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @assignment.title %>
</p>

<p>
  <b>Description:</b>
  <%= @assignment.description %>
</p>

<p>
  <b>Assignment type:</b>
  <%= @assignment.assignment_type %>
</p>

<p>
  <b><%= @assignment.clarify_start unless @assignment.clarify_start.nil? %></b>
  <%= @assignment.starts_at.strftime("%A %b. %-e, %Y, %l:%M%p") %>
</p>

<!-- <p>
  <b>Duration hours:</b>
  <%= @assignment.duration_hours %>
</p>

<p>
  <b>Duration minutes:</b>
  <%= @assignment.duration_minutes %>
</p> -->

<p>
  <b>Ends at:</b>
  <%= @assignment.ends_at.strftime("%A %b. %-e, %Y, %l:%M%p") %>
</p>


<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>

app/views/calendars/show.html.erb
<%= link_to "new assignment", new_assignment_path %>

<div id='calendar'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChronicCal4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>